import type { Metadata , Viewport} from 'next'
// These styles apply to every route in the application
import './globals.css'
import MobileNavbar from './components/menunavbar'
import DesktopNavbar from './components/desktopnavbar'
 
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <MobileNavbar />
        <DesktopNavbar />
        {children}
        </body>
    </html>
  )
}